const BBBBBBBBBBB = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
  + 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDB';

//       console.log(BBBBBBBBBBB);  10
//
//
const KKK = 11;
const KKK12 = 11;
var KKK13=11;
KKK13="`date`";
KKK = '11'
